# Generated by Django 6.0.5 on 2026-07-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('L', 'کم'), ('M', 'متوسط'), ('H', 'زیاد')], default='L', max_length=1)),
                ('status', models.CharField(choices=[('O', 'باز'), ('IP', 'درحال بررسی'), ('R', 'حل شده'), ('C', 'بسته شده')], default='O', max_length=2)),
                ('category', models.CharField(choices=[('H', 'سخت افزار'), ('S', 'نرم افزار'), ('N', 'شبکه'), ('OTH', 'سایر')], default='OTH', max_length=3)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
